server.port=8080
spring.application.name=auth-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_cursos_online
spring.datasource.username=postgres
spring.datasource.password=Server-2025
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=4a6b8c2d9e1f0a3b5c7d9e2f4a6b8c1d9e0f2a4b6c8d0e1f3a5b7c9d1e3f5a7b
jwt.expiration=28800000

# Logging
logging.level.com.cursoonline=DEBUG
logging.level.org.springframework.security=INFO

spring.threads.virtual.enabled=true