server.port=8080
spring.application.name=auth-backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_cursos_online
spring.datasource.username=postgres
spring.datasource.password=Server-2025
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=cursoonline_secreto_2026_minimo_32_caracteres_aqui
jwt.expiration=28800000

# Logging
logging.level.com.cursoonline=DEBUG
logging.level.org.springframework.security=INFO